title: Jeremy Rich's Site
email: jeremy.rich@berjak.com.au
description: >
  A site for managing Jeremy Rich's projects and documentation.
baseurl: "" # the subpath of your site, e.g. /blog or "" for the root
url: "http://jeremyrich.github.io/turbo-octo-spork" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
